// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendshipStatus string

const (
	FriendshipStatusPending  FriendshipStatus = "pending"
	FriendshipStatusAccepted FriendshipStatus = "accepted"
	FriendshipStatusBlocked  FriendshipStatus = "blocked"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus `json:"friendship_status"`
	Valid            bool             `json:"valid"` // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type PlaylistType string

const (
	PlaylistTypeWeekly  PlaylistType = "weekly"
	PlaylistTypeMonthly PlaylistType = "monthly"
)

func (e *PlaylistType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaylistType(s)
	case string:
		*e = PlaylistType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaylistType: %T", src)
	}
	return nil
}

type NullPlaylistType struct {
	PlaylistType PlaylistType `json:"playlist_type"`
	Valid        bool         `json:"valid"` // Valid is true if PlaylistType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaylistType) Scan(value interface{}) error {
	if value == nil {
		ns.PlaylistType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaylistType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaylistType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaylistType), nil
}

type PlaylistVisibility string

const (
	PlaylistVisibilityPublic     PlaylistVisibility = "public"
	PlaylistVisibilityFriends    PlaylistVisibility = "friends"
	PlaylistVisibilityPrivate    PlaylistVisibility = "private"
	PlaylistVisibilityUnreleased PlaylistVisibility = "unreleased"
)

func (e *PlaylistVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaylistVisibility(s)
	case string:
		*e = PlaylistVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaylistVisibility: %T", src)
	}
	return nil
}

type NullPlaylistVisibility struct {
	PlaylistVisibility PlaylistVisibility `json:"playlist_visibility"`
	Valid              bool               `json:"valid"` // Valid is true if PlaylistVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaylistVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PlaylistVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaylistVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaylistVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaylistVisibility), nil
}

type Role string

const (
	RoleUser  Role = "user"
	RoleAdmin Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Friendship struct {
	UserAID     uuid.UUID          `json:"user_a_id"`
	UserBID     uuid.UUID          `json:"user_b_id"`
	RequesterID uuid.UUID          `json:"requester_id"`
	Status      FriendshipStatus   `json:"status"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
}

type InviteCode struct {
	Code       string             `json:"code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RedeemedBy uuid.UUID          `json:"redeemed_by"`
	RedeemedAt pgtype.Timestamptz `json:"redeemed_at"`
}

type Playlist struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Type       PlaylistType       `json:"type"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Visibility PlaylistVisibility `json:"visibility"`
	ImageUrl   string             `json:"image_url"`
	Year       int32              `json:"year"`
	Month      int32              `json:"month"`
	Day        int32              `json:"day"`
}

type PrivateKey struct {
	Kid   int32  `json:"kid"`
	Value string `json:"value"`
}

type SpotifyPlay struct {
	UserID   uuid.UUID          `json:"user_id"`
	TrackID  string             `json:"track_id"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

type SpotifyPlaylistTrack struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	TrackID    string    `json:"track_id"`
	Plays      int32     `json:"plays"`
}

type SpotifyToken struct {
	UserID       string             `json:"user_id"`
	AccessToken  string             `json:"access_token"`
	TokenType    string             `json:"token_type"`
	Scope        string             `json:"scope"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpires pgtype.Timestamptz `json:"token_expires"`
}

type SpotifyTrack struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Artists    []string           `json:"artists"`
	Popularity int32              `json:"popularity"`
	Href       string             `json:"href"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	Raw        []byte             `json:"raw"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Username           pgtype.Text        `json:"username"`
	Email              string             `json:"email"`
	ImageUrl           pgtype.Text        `json:"image_url"`
	SpotifyID          pgtype.Text        `json:"spotify_id"`
	SpotifyDisplayName pgtype.Text        `json:"spotify_display_name"`
	SpotifyUrl         pgtype.Text        `json:"spotify_url"`
	SpotifyData        []byte             `json:"spotify_data"`
	RegisteredAt       pgtype.Timestamptz `json:"registered_at"`
	Role               Role               `json:"role"`
	Password           pgtype.Text        `json:"password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RefreshToken       string             `json:"refresh_token"`
	RefreshExpiresAt   pgtype.Timestamptz `json:"refresh_expires_at"`
}
