// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendshipStatus string

const (
	FriendshipStatusPending  FriendshipStatus = "pending"
	FriendshipStatusAccepted FriendshipStatus = "accepted"
	FriendshipStatusRejected FriendshipStatus = "rejected"
	FriendshipStatusBlocked  FriendshipStatus = "blocked"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus
	Valid            bool // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type PlaylistVisibility string

const (
	PlaylistVisibilityPublic  PlaylistVisibility = "public"
	PlaylistVisibilityFriends PlaylistVisibility = "friends"
	PlaylistVisibilityPrivate PlaylistVisibility = "private"
)

func (e *PlaylistVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaylistVisibility(s)
	case string:
		*e = PlaylistVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaylistVisibility: %T", src)
	}
	return nil
}

type NullPlaylistVisibility struct {
	PlaylistVisibility PlaylistVisibility
	Valid              bool // Valid is true if PlaylistVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaylistVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PlaylistVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaylistVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaylistVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaylistVisibility), nil
}

type Friendship struct {
	UserAID     uuid.UUID
	UserBID     uuid.UUID
	Status      FriendshipStatus
	RequestedAt pgtype.Timestamp
	RespondedAt pgtype.Timestamp
}

type MonthlyPlaylist struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Tracks     [][]byte
	Year       int16
	Month      int16
	Name       string
	CreatedAt  pgtype.Timestamptz
	Visibility PlaylistVisibility
}

type PrivateKey struct {
	Kid   int32
	Value string
}

type SpotifyToken struct {
	UserID       string
	AccessToken  string
	TokenType    string
	Scope        string
	RefreshToken string
}

type User struct {
	ID               uuid.UUID
	SpotifyUserID    string
	Email            string
	SpotifyUserData  []byte
	CreatedAt        pgtype.Timestamp
	RefreshToken     uuid.UUID
	RefreshExpiresAt pgtype.Timestamp
}
