services:
  postgres:
    image: postgres:17
    container_name: hathr-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hathr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
  redis:
    image: redis:7.4.1
    container_name: boshi-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boshi-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
