apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hathr
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: jwks-volume
          configMap:
            name: jwks-config
            items:
              - key: jwks.json
                path: jwks.json
      containers:
        - name: backend
          image: matthew10125/hathr-backend
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "${DB_URL}"
            - name: PORT
              value: "${PORT}"
            - name: SPOTIFY_CLIENT_ID
              value: "${SPOTIFY_CLIENT_ID}"
            - name: SPOTIFY_CLIENT_SECRET
              value: "${SPOTIFY_CLIENT_SECRET}"
            - name: SPOTIFY_REDIRECT_URI
              value: "${SPOTIFY_REDIRECT_URI}"
            - name: IMAGE_GENERATOR_URL
              value: "${IMAGE_GENERATOR_URL}"
            - name: IMAGE_GENERATOR_API_KEY
              value: "${IMAGE_GENERATOR_API_KEY}"
            - name: S3_URL
              value: "${S3_URL}"
            - name: ORIGIN_URL
              value: "${ORIGIN_URL}"
            - name: JWKS_PATH
              value: "/etc/jwks/jwks.json"
          volumeMounts:
            - name: jwks-volume
              mountPath: /etc/jwks
              subPath: jwks.json
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hathr
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
